language: java
jdk: openjdk8
dist: xenial
before_install:
  - ./gradlew clean jar
script:
  - ./gradlew test
after_success:
  - ./gradlew jacocoTestReport
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
