language: java
jdk:
  - oraclejdk8
  - oraclejdk9
dist: trusty
before_install:
  - ./gradlew clean jar
jobs:
  - COVERAGE=0.5 ./gradlew -p ./monolithic/ui check
  - COVERAGE=0.5 ./gradlew -p ./monolithic/service/cart check
  - COVERAGE=0.5 ./gradlew -p ./monolithic/service/user check
  - COVERAGE=0.3 ./gradlew -p ./monolithic/repository/order check
  - COVERAGE=0.5 ./gradlew -p ./monolithic/repository/cart check
  - COVERAGE=0.5 ./gradlew -p ./monolithic/repository/product check
  - COVERAGE=0.3 ./gradlew -p ./monolithic/repository/user check
deploy:
  provider: script
  script: echo 'WIP'
  on:
    all_branches: true
